[[libpsl]]
arch = "aarch64"
git-tree-sha1 = "68f05ba899673cecc58223c32cea084a72e595c7"
os = "macos"

    [[libpsl.download]]
    sha256 = "4d91c00a8bf71113f1869e303ed551c40bf12a26d6f33843e0f80bf0d71be807"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.2+0/libpsl.v0.23.2.aarch64-apple-darwin.tar.gz"
[[libpsl]]
arch = "aarch64"
git-tree-sha1 = "562dbdedfd5b6d11062a0bf326660ff61bc3f3e6"
libc = "glibc"
os = "linux"

    [[libpsl.download]]
    sha256 = "900a7298e4200b74808063fcec5039a2ad6d2c7f49c2c5637332701d0348c2e1"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.2+0/libpsl.v0.23.2.aarch64-linux-gnu.tar.gz"
[[libpsl]]
arch = "aarch64"
git-tree-sha1 = "542e1de704e12f1edbdd981322924b18d1197b6c"
libc = "musl"
os = "linux"

    [[libpsl.download]]
    sha256 = "edd558d76072bd8b271a9302e2ee6f8e168eb0803ba89aa3cb70b3df421a37bd"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.2+0/libpsl.v0.23.2.aarch64-linux-musl.tar.gz"
[[libpsl]]
arch = "aarch64"
git-tree-sha1 = "037021bf91f40045f465a4b9e066862804bbf035"
os = "freebsd"

    [[libpsl.download]]
    sha256 = "d221930eedb19bd34ea03d01689afe7ddf3b66bce17a92fb5ee6a7ba62dfcabf"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.2+0/libpsl.v0.23.2.aarch64-unknown-freebsd.tar.gz"
[[libpsl]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "efe95fbdd1756ddc3baa23194e61e49e2bd87bfe"
libc = "glibc"
os = "linux"

    [[libpsl.download]]
    sha256 = "ac93f7a17673a00d8b2ffed3faeadcfdd4167a4dfacdcac2dde8a2b8851a1706"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.2+0/libpsl.v0.23.2.armv6l-linux-gnueabihf.tar.gz"
[[libpsl]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "077eef42343615f0d943f9b678eb16ee56bec87e"
libc = "musl"
os = "linux"

    [[libpsl.download]]
    sha256 = "7035ff6b922b8ffa1093aaffc451a3a11b4f77b93b8ab44d82cbf3a84a469433"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.2+0/libpsl.v0.23.2.armv6l-linux-musleabihf.tar.gz"
[[libpsl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "548958bee048ed9732b3e9a68c23708aca7dcb5c"
libc = "glibc"
os = "linux"

    [[libpsl.download]]
    sha256 = "ed2f11a59a47b2c766bfc009a1fc57eaf78e1824ec335d7c6ad13b5e765caeed"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.2+0/libpsl.v0.23.2.armv7l-linux-gnueabihf.tar.gz"
[[libpsl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e47858953b5194dc26a43d504ebb223d9a800965"
libc = "musl"
os = "linux"

    [[libpsl.download]]
    sha256 = "3f632c845fccab129ac967bb3201cd505940f21d18996d693ae7ff348fee027e"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.2+0/libpsl.v0.23.2.armv7l-linux-musleabihf.tar.gz"
[[libpsl]]
arch = "i686"
git-tree-sha1 = "1f8f84dd7377eae3d48cb4ce230f1f969c816e50"
libc = "glibc"
os = "linux"

    [[libpsl.download]]
    sha256 = "32e60fc151443faf6e3c6e9379becad2de80cc07825b790bb6be150eece5968b"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.2+0/libpsl.v0.23.2.i686-linux-gnu.tar.gz"
[[libpsl]]
arch = "i686"
git-tree-sha1 = "11e9c7c5cc63f4931f89c54826ace6d6ead28861"
libc = "musl"
os = "linux"

    [[libpsl.download]]
    sha256 = "600a06c32fb9a70c21bf0ff5904158d41c22b9f420d2a4a901ba10415816c618"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.2+0/libpsl.v0.23.2.i686-linux-musl.tar.gz"
[[libpsl]]
arch = "i686"
git-tree-sha1 = "73f86daa660e0c429ca871e3ca7cc9f2083acc51"
os = "windows"

    [[libpsl.download]]
    sha256 = "2375602d11a1f3a3aa553453180d857b65aabc9235f1259e2530d75ee17e6470"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.2+0/libpsl.v0.23.2.i686-w64-mingw32.tar.gz"
[[libpsl]]
arch = "powerpc64le"
git-tree-sha1 = "6a72246718f1a19ac88c50a68fe2790404dd7452"
libc = "glibc"
os = "linux"

    [[libpsl.download]]
    sha256 = "325fc9c2dd38991019ddd6890b2f03279d170d99d0781e41b5e6d746683351a2"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.2+0/libpsl.v0.23.2.powerpc64le-linux-gnu.tar.gz"
[[libpsl]]
arch = "riscv64"
git-tree-sha1 = "c282f48c015e5f41a8d47aeed32afe839b0fc0eb"
libc = "glibc"
os = "linux"

    [[libpsl.download]]
    sha256 = "46097019bcf986fe7585ced8d29e4d96628f495cb32f52e2449860f5e5226c74"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.2+0/libpsl.v0.23.2.riscv64-linux-gnu.tar.gz"
[[libpsl]]
arch = "x86_64"
git-tree-sha1 = "4db97e6935378974e9cc24294fddc0c1f8e4b90f"
os = "macos"

    [[libpsl.download]]
    sha256 = "555d79ae69408c3b3ce1f3cc5ba9fc1c93726d2b15d800ebe377c15348687ef0"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.2+0/libpsl.v0.23.2.x86_64-apple-darwin.tar.gz"
[[libpsl]]
arch = "x86_64"
git-tree-sha1 = "497b278b75b756bd63d7dba7b2839d160b3b5025"
libc = "glibc"
os = "linux"

    [[libpsl.download]]
    sha256 = "27aaaf206608ccaed89ed0280ce19a1bbe8f05a6f1cb118cc5123cf82e656d77"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.2+0/libpsl.v0.23.2.x86_64-linux-gnu.tar.gz"
[[libpsl]]
arch = "x86_64"
git-tree-sha1 = "8bb791c8185f6092fc799c20b29658f1b9fa0477"
libc = "musl"
os = "linux"

    [[libpsl.download]]
    sha256 = "40b10576b9db8be6c38ffcd16a8b3b3b2ecc7d0e6310de407b76314b6fe7b599"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.2+0/libpsl.v0.23.2.x86_64-linux-musl.tar.gz"
[[libpsl]]
arch = "x86_64"
git-tree-sha1 = "07204a1aa523a28b4b2c7104be56ba596dca8c8a"
os = "freebsd"

    [[libpsl.download]]
    sha256 = "0071d43ba711253bd2abc16e6ef8a99d3b5b7b6a03d2010d9cbbdd8d40b67317"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.2+0/libpsl.v0.23.2.x86_64-unknown-freebsd.tar.gz"
[[libpsl]]
arch = "x86_64"
git-tree-sha1 = "3a4616381654c490fa867fe3bcbe2642ad5df7c0"
os = "windows"

    [[libpsl.download]]
    sha256 = "9c54aca7059a2fd63e4a91c29b0ae66ef12210981b4e440b745247671c5190ff"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.2+0/libpsl.v0.23.2.x86_64-w64-mingw32.tar.gz"
