[[libpsl]]
arch = "aarch64"
git-tree-sha1 = "50c72bc6a90eb756d82547d7d7a35986429eb837"
os = "macos"

    [[libpsl.download]]
    sha256 = "347a42c74a5abc64ba38ebef77830543403f2beb9605a85d0ad3984f045467a8"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.3+0/libpsl.v0.23.3.aarch64-apple-darwin.tar.gz"
[[libpsl]]
arch = "aarch64"
git-tree-sha1 = "4d9ff0d760e5a6d2cb04a43fe6e784a72652bcb3"
libc = "glibc"
os = "linux"

    [[libpsl.download]]
    sha256 = "8dd8c6c3e085076b4cefb0684ca048d0e7cfc5bf6cb1981fc700d7b865ff9868"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.3+0/libpsl.v0.23.3.aarch64-linux-gnu.tar.gz"
[[libpsl]]
arch = "aarch64"
git-tree-sha1 = "1b3b8d7226c83ec728321f773fdd64c46bc636df"
libc = "musl"
os = "linux"

    [[libpsl.download]]
    sha256 = "390bd393e30502094b8fcb4687633b23212e39e31db33954d88aa4820631bdcf"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.3+0/libpsl.v0.23.3.aarch64-linux-musl.tar.gz"
[[libpsl]]
arch = "aarch64"
git-tree-sha1 = "96d8beeedfa56ab6e202d903037a4a9775d33207"
os = "freebsd"

    [[libpsl.download]]
    sha256 = "690aaf5af74d484c72bc399fa66df04cc22fa59fef12640547f9c21529c4adf1"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.3+0/libpsl.v0.23.3.aarch64-unknown-freebsd.tar.gz"
[[libpsl]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bddffd3866702300ec4f83fb28a5e5a91d5ce326"
libc = "glibc"
os = "linux"

    [[libpsl.download]]
    sha256 = "96d7d63c84906b658a7ac711f337adee93d46d13a6e9ed155296eb6b28a2d6c6"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.3+0/libpsl.v0.23.3.armv6l-linux-gnueabihf.tar.gz"
[[libpsl]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "687d11feada09d6b308e59c2a4f876f0e194d277"
libc = "musl"
os = "linux"

    [[libpsl.download]]
    sha256 = "eda8565f00a7d81eb816164600fb30f5b8ce2491c3f9e2b6c8969a7684fca638"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.3+0/libpsl.v0.23.3.armv6l-linux-musleabihf.tar.gz"
[[libpsl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5586b59cf453932e71a018a8c106e71d54469b31"
libc = "glibc"
os = "linux"

    [[libpsl.download]]
    sha256 = "012505513195b7f39624b97ff4f28b7d551419402ca950c6a235810207c0d42d"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.3+0/libpsl.v0.23.3.armv7l-linux-gnueabihf.tar.gz"
[[libpsl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "abcb578f423159db8e22f28d63c46a4b7bdf8030"
libc = "musl"
os = "linux"

    [[libpsl.download]]
    sha256 = "bd82e0d669f18b5742f42d5d968b9959f26b6577701743ad953d434f4522850f"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.3+0/libpsl.v0.23.3.armv7l-linux-musleabihf.tar.gz"
[[libpsl]]
arch = "i686"
git-tree-sha1 = "96ffd328552a1da5d030823d83be38b65355fef2"
libc = "glibc"
os = "linux"

    [[libpsl.download]]
    sha256 = "53c5f85ae85ceba725d7b2aeffbce0a98d2141e8856309596bda1c43f6426391"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.3+0/libpsl.v0.23.3.i686-linux-gnu.tar.gz"
[[libpsl]]
arch = "i686"
git-tree-sha1 = "a5eb7ce2e65994fa12e58844931ef908ea5734e3"
libc = "musl"
os = "linux"

    [[libpsl.download]]
    sha256 = "a2a61faafc12e69d7973ae1a6ace183a20048ef98edbb7307295aab702936f10"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.3+0/libpsl.v0.23.3.i686-linux-musl.tar.gz"
[[libpsl]]
arch = "i686"
git-tree-sha1 = "146adc8dc8fc9caddb76a4fe5db0c2766f02f57d"
os = "windows"

    [[libpsl.download]]
    sha256 = "e82804b6294e42864273cab84895994684597cbf53f53838e4c1342e4fa5b419"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.3+0/libpsl.v0.23.3.i686-w64-mingw32.tar.gz"
[[libpsl]]
arch = "powerpc64le"
git-tree-sha1 = "20c5f2b5d7523393b62fb34a7b5b79fc9a463a79"
libc = "glibc"
os = "linux"

    [[libpsl.download]]
    sha256 = "578fe908c71a3f9a3878a2b4c237de73eeca3dfca1bc5c606c4cda23ad2d4380"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.3+0/libpsl.v0.23.3.powerpc64le-linux-gnu.tar.gz"
[[libpsl]]
arch = "riscv64"
git-tree-sha1 = "1d6c9d29c0aac2b483144e98044edaa172fc0e48"
libc = "glibc"
os = "linux"

    [[libpsl.download]]
    sha256 = "5a2f860eaca7502591d35321280010fe34fa408d8e5240cc5f1f3c422e764402"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.3+0/libpsl.v0.23.3.riscv64-linux-gnu.tar.gz"
[[libpsl]]
arch = "x86_64"
git-tree-sha1 = "38088cff5b96ba52ec8b936b239251be2795638d"
os = "macos"

    [[libpsl.download]]
    sha256 = "e9dc63d86272021ef96b3d1b05a044a0745e96d0b7db5932245849c9839ae642"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.3+0/libpsl.v0.23.3.x86_64-apple-darwin.tar.gz"
[[libpsl]]
arch = "x86_64"
git-tree-sha1 = "960b4b3ea31069fbc79cd48bd23deeb0d9d0dc1b"
libc = "glibc"
os = "linux"

    [[libpsl.download]]
    sha256 = "432b09d1a6c089de1cd005ce242558ab3e93159a99972a7d9ad342e12f7b8213"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.3+0/libpsl.v0.23.3.x86_64-linux-gnu.tar.gz"
[[libpsl]]
arch = "x86_64"
git-tree-sha1 = "b2627e1468fb68dfb9d6ad72f505679c2be395cb"
libc = "musl"
os = "linux"

    [[libpsl.download]]
    sha256 = "b36b33b8509c8b1221323859f9555f66e049bc1ef7aa7effbbfa28d1337732c5"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.3+0/libpsl.v0.23.3.x86_64-linux-musl.tar.gz"
[[libpsl]]
arch = "x86_64"
git-tree-sha1 = "ef93bd985a5338f907462229200c6d3dfd930c40"
os = "freebsd"

    [[libpsl.download]]
    sha256 = "4dff11cb340361bc9c198b477ab0e089815e7fe2549f25fac3a591a2c51f7123"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.3+0/libpsl.v0.23.3.x86_64-unknown-freebsd.tar.gz"
[[libpsl]]
arch = "x86_64"
git-tree-sha1 = "a046295a6d3f66112a6267dd143fe0ea15d0cb98"
os = "windows"

    [[libpsl.download]]
    sha256 = "62af3e226917b08148a50d7a8a047e6a375c75414abd4c1a4f657c64fc24d4d5"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.3+0/libpsl.v0.23.3.x86_64-w64-mingw32.tar.gz"
