[[libpsl]]
arch = "aarch64"
git-tree-sha1 = "f4a71715d8598ee2aa4ebea847fcf6c0c8297eca"
os = "macos"

    [[libpsl.download]]
    sha256 = "53c21715970d23b4e7123ce35de7d0827c6993df15a2117e962693d5ba77837b"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.21.5+0/libpsl.v0.21.5.aarch64-apple-darwin.tar.gz"
[[libpsl]]
arch = "aarch64"
git-tree-sha1 = "637d9a4dc4d28a69feaf8af2a7b7c414e7fa8775"
libc = "glibc"
os = "linux"

    [[libpsl.download]]
    sha256 = "845716a9e01ccec0e03ffda0ca157a86ea799f688464d694b9441ed40b31dbde"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.21.5+0/libpsl.v0.21.5.aarch64-linux-gnu.tar.gz"
[[libpsl]]
arch = "aarch64"
git-tree-sha1 = "e8430363731b906665121bbeb0940ed4309ac747"
libc = "musl"
os = "linux"

    [[libpsl.download]]
    sha256 = "0ffc724a529c74fffe806b41f8d1ea0aae2badd554e2eb8421e336e7142fce24"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.21.5+0/libpsl.v0.21.5.aarch64-linux-musl.tar.gz"
[[libpsl]]
arch = "aarch64"
git-tree-sha1 = "18bb456e80d59b520f64a241797a1a6a81779022"
os = "freebsd"

    [[libpsl.download]]
    sha256 = "4c118e7fddd545bf8a597ee541b5003f65d51a68360aa32cadc31256a2ebdb4f"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.21.5+0/libpsl.v0.21.5.aarch64-unknown-freebsd.tar.gz"
[[libpsl]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6a67b1d24e7b8b7327daf176a51dd15b402d7f63"
libc = "glibc"
os = "linux"

    [[libpsl.download]]
    sha256 = "203aef38588fd04c47614db9ce1d86df3a4ac3daeb33c39ef4213533aad8353f"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.21.5+0/libpsl.v0.21.5.armv6l-linux-gnueabihf.tar.gz"
[[libpsl]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "690e62ec6eeec8554116ab980a862dade80e31c1"
libc = "musl"
os = "linux"

    [[libpsl.download]]
    sha256 = "bbb1f0269120c0f909155225bba95dd79fb85a18503e3e104b0057c2485b760c"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.21.5+0/libpsl.v0.21.5.armv6l-linux-musleabihf.tar.gz"
[[libpsl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1a06c3a1b54ab05e6041c8e7fbfc635f0522622b"
libc = "glibc"
os = "linux"

    [[libpsl.download]]
    sha256 = "404e7d7d45381336f5e816d8898480adb0cdfeebc8bb2e596754b6741eeed9cf"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.21.5+0/libpsl.v0.21.5.armv7l-linux-gnueabihf.tar.gz"
[[libpsl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9188ce28f67e65b8755333ed84f06f6f88d23e44"
libc = "musl"
os = "linux"

    [[libpsl.download]]
    sha256 = "459d0ee9fadd06b48711846b28ffa078de374a343b1208d14ffa50300375647e"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.21.5+0/libpsl.v0.21.5.armv7l-linux-musleabihf.tar.gz"
[[libpsl]]
arch = "i686"
git-tree-sha1 = "226862c53a4ca04338cd5cc180aeac383ff867ee"
libc = "glibc"
os = "linux"

    [[libpsl.download]]
    sha256 = "1d3a0eea9d1840003ca1376617216801ba0d42f3aaaebbdeda725cc3061d9588"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.21.5+0/libpsl.v0.21.5.i686-linux-gnu.tar.gz"
[[libpsl]]
arch = "i686"
git-tree-sha1 = "7bc2032c7b2c291c2fb0396ca951b95d8d3d326f"
libc = "musl"
os = "linux"

    [[libpsl.download]]
    sha256 = "d92dbb6fc74ccf9286a4c73fb38fd479a6ef51f5cdf5ca5a310b5ae858e0b0cd"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.21.5+0/libpsl.v0.21.5.i686-linux-musl.tar.gz"
[[libpsl]]
arch = "i686"
git-tree-sha1 = "f8f1a1149bb14bfe094ef3168aebec9f0f642267"
os = "windows"

    [[libpsl.download]]
    sha256 = "54ea3b91b58b8d856af409db125a1f8fce3ae6659427f77d613797229e6ecc7a"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.21.5+0/libpsl.v0.21.5.i686-w64-mingw32.tar.gz"
[[libpsl]]
arch = "powerpc64le"
git-tree-sha1 = "b98e1133e2c429ec836306049c433e856d7eedc9"
libc = "glibc"
os = "linux"

    [[libpsl.download]]
    sha256 = "cfff5126c2191dd552775a86cd4ace761774d0e2ea820351bcb94492fb870c30"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.21.5+0/libpsl.v0.21.5.powerpc64le-linux-gnu.tar.gz"
[[libpsl]]
arch = "x86_64"
git-tree-sha1 = "fe4e0250f478805ffff1c1bcd9be5a3d5796fee5"
os = "macos"

    [[libpsl.download]]
    sha256 = "b6b55e992897a27aedd72d41c369a7668f32aaf432976b0ca3499e2ea70c2490"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.21.5+0/libpsl.v0.21.5.x86_64-apple-darwin.tar.gz"
[[libpsl]]
arch = "x86_64"
git-tree-sha1 = "bbed2f7fcffa50ef2220bda51c06d75fcf472e76"
libc = "glibc"
os = "linux"

    [[libpsl.download]]
    sha256 = "1c38a184a450ff2812f87505091ea2dab0ccd86a3d981e28972c015c263f76e7"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.21.5+0/libpsl.v0.21.5.x86_64-linux-gnu.tar.gz"
[[libpsl]]
arch = "x86_64"
git-tree-sha1 = "b31b5aa02548cd182b1e0491e667bcfb4f017952"
libc = "musl"
os = "linux"

    [[libpsl.download]]
    sha256 = "b0d743aca00b171756c17729923e07749964619ddc9154f6a177d07e70c35c10"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.21.5+0/libpsl.v0.21.5.x86_64-linux-musl.tar.gz"
[[libpsl]]
arch = "x86_64"
git-tree-sha1 = "b2d1b773d65fbf0cbb9d595e048914d1432c51f6"
os = "freebsd"

    [[libpsl.download]]
    sha256 = "adb71486438952fba379555f46684b9491239b08acb5cea083aa1422b1e351bc"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.21.5+0/libpsl.v0.21.5.x86_64-unknown-freebsd.tar.gz"
[[libpsl]]
arch = "x86_64"
git-tree-sha1 = "ed051052cc71f45a1fb4cabaca2e1f3689e1b51c"
os = "windows"

    [[libpsl.download]]
    sha256 = "132a0b3d0bb5ae2320dcf9d58bfcf9840b78b3896e98c848c54d9866b6735ac1"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.21.5+0/libpsl.v0.21.5.x86_64-w64-mingw32.tar.gz"
