[[libpsl]]
arch = "aarch64"
git-tree-sha1 = "a46f2f2136c8195c8bfc31265ae06b984870b3d8"
os = "macos"

    [[libpsl.download]]
    sha256 = "e07abdb6627592e36eccee6a24e81d7d4f91119aec056abd2db84437cbafb538"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.1+0/libpsl.v0.23.1.aarch64-apple-darwin.tar.gz"
[[libpsl]]
arch = "aarch64"
git-tree-sha1 = "91539ae283a79f8f2fab1cadb4981f27dbafa452"
libc = "glibc"
os = "linux"

    [[libpsl.download]]
    sha256 = "1494b04ead9717d356bb492c4dc8004cf176193e691fb24c6a0b4b47fcc30b61"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.1+0/libpsl.v0.23.1.aarch64-linux-gnu.tar.gz"
[[libpsl]]
arch = "aarch64"
git-tree-sha1 = "c53e7690510d72cf0677f80226df181761b89055"
libc = "musl"
os = "linux"

    [[libpsl.download]]
    sha256 = "e06a5ea0e7de5b36e054c93c557bd25a42a64059bed8f57eeec61e85b43a5ca0"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.1+0/libpsl.v0.23.1.aarch64-linux-musl.tar.gz"
[[libpsl]]
arch = "aarch64"
git-tree-sha1 = "bc5dc716f8567108251978f71558d7b170ce52ab"
os = "freebsd"

    [[libpsl.download]]
    sha256 = "4074bfcb43e0fc2cd8fb580f12be62d0fe1595824ef6d9a9f4bbf0a9d1c6c2e8"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.1+0/libpsl.v0.23.1.aarch64-unknown-freebsd.tar.gz"
[[libpsl]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c4b0d106c7408989b00a17559f199f4735d6cbbe"
libc = "glibc"
os = "linux"

    [[libpsl.download]]
    sha256 = "3549644f1bb8a3a310b069e6d00f97f90b54d722f3b0d93b15b84ab2d3295caa"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.1+0/libpsl.v0.23.1.armv6l-linux-gnueabihf.tar.gz"
[[libpsl]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ce92bc84b2a1bd200fefa3f42ee4ad096f5a6edb"
libc = "musl"
os = "linux"

    [[libpsl.download]]
    sha256 = "db0b3f653692656d9874b4776a69a91fa4bd1f17c96cbafa2beed56210a4fe57"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.1+0/libpsl.v0.23.1.armv6l-linux-musleabihf.tar.gz"
[[libpsl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1df7025d4b8601c9b9c32d40c9b89ce7f7c741a3"
libc = "glibc"
os = "linux"

    [[libpsl.download]]
    sha256 = "b807376b735456a6723a99c24fa156a13435ddad64a3ebfc652aa12aaf4c4388"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.1+0/libpsl.v0.23.1.armv7l-linux-gnueabihf.tar.gz"
[[libpsl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6bd319e10296e4162cf800db98a3531bfc0d2ebe"
libc = "musl"
os = "linux"

    [[libpsl.download]]
    sha256 = "466158252735fc19883a4e8c908e25db9a290eda17cac4dbc15469547593dff6"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.1+0/libpsl.v0.23.1.armv7l-linux-musleabihf.tar.gz"
[[libpsl]]
arch = "i686"
git-tree-sha1 = "0ea4010f1b8210c442655698a05108f800041767"
libc = "glibc"
os = "linux"

    [[libpsl.download]]
    sha256 = "15737d2c5746acc5a46ce392c53765e179b0fcb9aff58beada3a41bcc9027c5f"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.1+0/libpsl.v0.23.1.i686-linux-gnu.tar.gz"
[[libpsl]]
arch = "i686"
git-tree-sha1 = "2a6d39ba694066b84d6de1dc9a11f91660442274"
libc = "musl"
os = "linux"

    [[libpsl.download]]
    sha256 = "7739fe384a2e7c9e7d31ab1be79584971cfe21fac651c74483dfa144e90a828f"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.1+0/libpsl.v0.23.1.i686-linux-musl.tar.gz"
[[libpsl]]
arch = "i686"
git-tree-sha1 = "6b9aa64f7972364a64c60a136abc3cbbe4f17d09"
os = "windows"

    [[libpsl.download]]
    sha256 = "7adc16379ca3f13ddad11fbf70c085e35fc538b3be47ad4c18e627e1a0193c43"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.1+0/libpsl.v0.23.1.i686-w64-mingw32.tar.gz"
[[libpsl]]
arch = "powerpc64le"
git-tree-sha1 = "2f2d26d87c7bc2cf6c55a787e95d5818e018da4d"
libc = "glibc"
os = "linux"

    [[libpsl.download]]
    sha256 = "3b287bb5bffa589afd10341900b7a72199e4f79cb9966d3ab99cf16d3398c06d"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.1+0/libpsl.v0.23.1.powerpc64le-linux-gnu.tar.gz"
[[libpsl]]
arch = "riscv64"
git-tree-sha1 = "8f8855f7340b99cc896b5a51e7139d675f8eefca"
libc = "glibc"
os = "linux"

    [[libpsl.download]]
    sha256 = "aa950c25e22427186911d553594a28e8deefded3164b3dec738a60144b8b14b1"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.1+0/libpsl.v0.23.1.riscv64-linux-gnu.tar.gz"
[[libpsl]]
arch = "x86_64"
git-tree-sha1 = "52af6d83defbd0ca3c6e06b2e22161e94add9709"
os = "macos"

    [[libpsl.download]]
    sha256 = "9cb100286a36dccc6ace06fb48d9644675d309a6d70cf78f2a98181140510384"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.1+0/libpsl.v0.23.1.x86_64-apple-darwin.tar.gz"
[[libpsl]]
arch = "x86_64"
git-tree-sha1 = "bb1323efc0c6d04913e7d62ffa475725651d6690"
libc = "glibc"
os = "linux"

    [[libpsl.download]]
    sha256 = "59645e202e1f06ede4bce831f5e3aa33f6618248da5c45d9d64d93f79ac91dd1"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.1+0/libpsl.v0.23.1.x86_64-linux-gnu.tar.gz"
[[libpsl]]
arch = "x86_64"
git-tree-sha1 = "6d4c8900579f3acd2584ed6e19f9b41eb2900356"
libc = "musl"
os = "linux"

    [[libpsl.download]]
    sha256 = "d48a7799500fd7198f80628379305c1f0e072456408bd0de1fff69a0ab94cf73"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.1+0/libpsl.v0.23.1.x86_64-linux-musl.tar.gz"
[[libpsl]]
arch = "x86_64"
git-tree-sha1 = "97b90a145b7565503d4027a0bf2d08ca678aac6c"
os = "freebsd"

    [[libpsl.download]]
    sha256 = "bc45e77a82a8b454dae41fb45b55200d84b2b39494067b0f1541204889576c10"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.1+0/libpsl.v0.23.1.x86_64-unknown-freebsd.tar.gz"
[[libpsl]]
arch = "x86_64"
git-tree-sha1 = "1f67692878ead51e85aa832f49fcf678eef34f6a"
os = "windows"

    [[libpsl.download]]
    sha256 = "a83b5376338ec2205e807560aee989b19632b87c29567490cae5c7017f07d29b"
    url = "https://github.com/JuliaBinaryWrappers/libpsl_jll.jl/releases/download/libpsl-v0.23.1+0/libpsl.v0.23.1.x86_64-w64-mingw32.tar.gz"
